trigger:
  branches:
    include:
    - main

resources:
  repositories:
    - repository: templates
      type: git
      name: Plumbing/core-templates
    - repository: protobuf.js
      type: git
      name: Open/protobuf.js

stages:
- template: stages/sync/sync.yml@templates  # Template reference
  parameters:
    checkout: protobuf.js
